spring:
  application:
    name: user-service

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /user-service/v3/api-docs/swagger-config
    url: /user-service/v3/api-docs
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}