spring:
  application:
    name: notification-service

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

app:
  kafka:
    topics:
      payment-confirmed: payment-service.payment-confirmed
      payment-failed: payment-service.payment-failed
    dlt-topic:
      notification-service: notification.service.dlt